name: myfirstagent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - langchain
  - langchain-deepseek
  - requests
  - feedparser
  - pyyaml
  - pytest
  - pytest-cov
  - requests-mock
  - arize-phoenix-otel
  - openinference-instrumentation-langchain
  - python-telegram-bot
  - apscheduler
  - oci-cli
