name: myfirstagent
channels:
  - conda-forge
dependencies:
  - python=3.11
  - langchain
  - langchain-deepseek
  - requests
  - feedparser
  - pytest
  - requests-mock
  - arize-phoenix-otel
  - openinference-instrumentation-langchain
  - python-telegram-bot
